language: python3

script:
  - pytest

install:
  - python3 -m pip install -r requirements.txt

addons:
  apt:
    update: true
    packages:
    - freeglut3-dev
    - python3-gi
    - python3-gi-cairo
